.TH opx-alm-service "1" "2018-06-11" OPX "OPX services"
.SH NAME
opx-alm-service \- OPX alarm service
.SH SYNOPSIS
.SY opx-alm-service
.OP \-f file
.OP \-\-file file
.YS
.SH DESCRIPTION
This service monitors system status, and as status changes, it drives front-panel LEDs to indicate status.
.PP
It also maintains current system status, in the form of a list of outstanding alarm conditions, which can be queried via the CPS API base-alms/active-alms object.
.SH OPTIONS
.TP
\fB\-f\fR \fIfile\fR, \fB\-\-file\fR \fIfile\fR
Specify a JSON file configuration file, describing what events to monitor, and how to drive front-panel LEDs.
.br
If this option is not given, the default configuration file is /etc/opx/alms/config.json.
.SH EXIT STATUS
This is intended to be a long-lived service, started by systemd, always running while the system is up.
.br
If it does exit, with exit code 1, an error in reading the configuration file occurred.
.SH FILES
.TP
/etc/opx/alms/config.json
Default configuration file
.SH REPORTING BUGS
To report any OPX software bugs, see https://github.com/open-switch/opx-docs/wiki/Report-bugs.
.SH COPYRIGHT
\(co 2018 Dell Inc. or its subsidiaries. All Rights Reserved.
.SH SEE ALSO
opx-show-alms(1), opx-alm-service(5)
